services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb
    ports:
      - 3306:3306
    volumes:
      - database:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env  
    restart: always

  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress
    ports:
      - 9000:9000
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - inception
    env_file:
      - .env
    restart: always

  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - inception
    restart: always  

volumes:
  database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/rarraji/data/database
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/rarraji/data/wordpress

networks:
  inception:
    driver: bridge
